version: '3.7'
services:
  elasticsearch-master:
    image: elasticsearch:8.5.3
    container_name: elasticsearch-master
    environment:
      - "ES_JAVA_OPTS=-Xss512k -XX:NewRatio=1 -Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/master/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/master/data:/usr/share/elasticsearch/data
      - ./elasticsearch/master/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch/master/plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - net-es
  elasticsearch-slave:
    image: elasticsearch:8.5.3
    container_name: elasticsearch-slave
    environment:
      - "ES_JAVA_OPTS=-Xss512k -XX:NewRatio=1 -Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/slave/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/slave/data:/usr/share/elasticsearch/data
      - ./elasticsearch/slave/logs:/usr/share/elasticsearch/logs
    ports:
      - "9201:9201"
      - "9301:9301"
    networks:
      - net-es
    depends_on:
      - elasticsearch-master
  kibana:
    image: kibana:8.5.3
    container_name: kibana
    environment:
      - SERVER_NAME=kibana-server
      - ELASTICSEARCH_HOSTS=http://elasticsearch-master:9200
      - I18N_LOCALE=zh-CN
    ports:
      - "5601:5601"
    networks:
      - net-es
    depends_on:
      - elasticsearch-master
  elasticvue:
    image: cars10/elasticvue:1.0.4
    container_name: elasticvue
    ports:
      - "18080:8080"
    networks:
      - net-es
    depends_on:
      - elasticsearch-master
networks:
  net-es:
    driver: bridge